### ISSUE TITLE
Error: An API error occurred: user_not_found

### ISSUE THREAD

**Issue by andystumpf** [dangarfield/slack-back-static#2] opened 2022-11-01 19:31 UTC
Hello!  I've followed the setup and when running `npm start` it finds my first channel, and discovers all the messages in that channel, but when it proceeds to the next channel I get this error:

```
name@MacBook-Pro slack-back-static-main % node app.js
channel im -> all undefined C0XXXXXXX
       Found  200 messages
       Found  400 messages
       Found  600 messages
       Found  800 messages
       Found  1000 messages
       Found  1123 messages
channel im -> channel-name undefined XXXXXXXX
/Users/name/Documents/GitHub/slack-back-static-main/node_modules/@slack/web-api/dist/errors.js:51
    const error = errorWithCode(new Error(An API error occurred: ${result.error}), ErrorCode.PlatformError);
                                ^

Error: An API error occurred: user_not_found
    at platformErrorFromResult (/Users/name/Documents/GitHub/slack-back-static-main/node_modules/@slack/web-api/dist/errors.js:51:33)
    at WebClient.apiCall (/Users/name/Documents/GitHub/slack-back-static-main/node_modules/@slack/web-api/dist/WebClient.js:171:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getUserName (/Users/name/Documents/GitHub/slack-back-static-main/app.js:15:25)
    at async /Users/name/Documents/GitHub/slack-back-static-main/app.js:113:34 {
  code: 'slack_webapi_platform_error',
  data: {
    ok: false,
    error: 'user_not_found',
    response_metadata: {
      scopes: [
        'identify',           'channels:history',
        'im:history',         'mpim:history',
        'channels:read',      'emoji:read',
        'files:read',         'groups:read',
        'im:read',            'mpim:read',
        'reactions:read',     'search:read',
        'team:read',          'users:read',
        'users:read.email',   'usergroups:read',
        'users.profile:read', 'remote_files:read'
      ],
      acceptedScopes: [ 'users:read' ]
    }
  }
}

```
Node.js v18.12.0

I'm not sure I have the SLACK_SPACE correct.  Would it be a string of 9 numbers and letters?

**Comment by dangarfield** [comment] 2022-11-01 19:34
I'll take a look tomorrow morning if that's ok.

**Comment by dangarfield** [comment] 2022-11-02 11:50
@andystumpf I've just updated the readme with a few visuals to show exactly how to set and get the .env vars. Can you go through the readme again and validate whether that solves your issue?

If it does, great! If it doesn't I'll look and see what the issue is specifically with the `user_not_found` error so that I can fix it properly.

Thanks

**Comment by andystumpf** [comment] 2022-11-02 14:33
Hey @dangarfield Thanks for the fast update.  My setup seems to be just like yours.  I installed dependences `npm i`. My .env file is:
```
SLACK_BOT_TOKEN=xoxp-XXXXXXXX5-XXXXXXXXXXX305-430XXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXX
SLACK_SPACE=TXXXXXX5
#STATIC_PASSWORD=123
```
I'm using the User OAuth Token from Slack and have all the User Token Scopes you have listed.  
![Screenshot 2022-11-02 at 9 30 31 AM](https://user-images.githubusercontent.com/52007629/199516472-402e6f1d-7e0e-4cf3-bdcb-5a9d35392208.png)

It doesn't look like a Slack permission issue since it does connect and counts the messages from the first channel.  It looks like the problem is `Error: An API error occurred: user_not_found`

Thanks for your help!

**Comment by dangarfield** [comment] 2022-11-02 15:04
Strange, I've just tried with private, archived and closed and added one potential new scope required, but I don't think that that would solve your problem. Is the `channel-name` channel a shared channel across teams? I've just added an extra bit of logging. Can you pull and run again. If you could see let me know what you get in the `Channel details` logging statements (for the channels `all` and `channel-name`, that would be great.

_(Obviously, please obfuscate any private details etc)_

**Comment by andystumpf** [comment] 2022-11-02 16:22
Is the channel-name channel a shared channel across teams?  Its a read-only public channel that is visible to all users in the workspace
Not sure it's worth noting, it's `is_read_only: true` .  Is it possible to select a specific channel to test if the issue is with a channel?

Here are the logging.  Thanks again for the quick responses! 

```
% node app.js
Fetching channel - XXXXXXX -> Channel: channel-name
Channel details {
  ok: true,
  channel: {
    id: 'XXXXXXX',
    name: ‘channel-name,
    is_channel: true,
    is_group: false,
    is_im: false,
    is_mpim: false,
    is_private: false,
    created: XXXXXXX,
    is_archived: false,
    is_general: true,
    unlinked: 0,
    name_normalized: 'channel-name',
    is_shared: false,
    is_org_shared: false,
    is_pending_ext_shared: false,
    pending_shared: [],
    context_team_id: 'TXXXXXX5',
    parent_conversation: null,
    creator: 'UXXXXXXB',
    is_read_only: true,
    is_thread_only: false,
    is_non_threadable: false,
    is_ext_shared: false,
    shared_team_ids: [ 'TXXXXXXX5' ],
    pending_connected_team_ids: [],
    is_member: true,
    last_read: ‘XXXXXXXXXXXXXX’,
    topic: {
      value: 'Used to share info’,
      creator: 'UXXXXXXX3',
      last_set: XXXXXXXX
    },
    purpose: {
      value: ‘XXXXXXXXXXXXX.’,
      creator: 'UXXXXXXB',
      last_set: XXXXXXX
    },
    previous_names: [ 'channel-name2’, 'channel-name3’ ]
  },
  response_metadata: {
    scopes: [
      'identify',
      'channels:history',
      'im:history',
      'mpim:history',
      'channels:read',
      'files:read',
      'groups:read',
      'im:read',
      'mpim:read',
      'users:read',
      'remote_files:read'
    ],
    acceptedScopes: [ 'channels:read', 'groups:read', 'mpim:read', 'im:read', 'read' ]
  }
}
       Found  200 messages
       Found  400 messages
       Found  600 messages
       Found  800 messages
       Found  1000 messages
       Found  1123 messages
Fetching channel - CXXXXXXXXP -> Channel: channel-name5
Channel details {
  ok: true,
  channel: {
    id: 'CXXXXXX5P',
    name: 'channel-name5’,
    is_channel: true,
    is_group: false,
    is_im: false,
    is_mpim: false,
    is_private: false,
    created: XXXXXXXXX,
    is_archived: false,
    is_general: false,
    unlinked: 0,
    name_normalized: 'channel-name5’,
    is_shared: false,
    is_org_shared: false,
    is_pending_ext_shared: false,
    pending_shared: [],
    context_team_id: ‘XXXXXXXXX’,
    parent_conversation: null,
    creator: ‘XXXXXXXXXX’,
    is_ext_shared: false,
    shared_team_ids: [ 'XXXXXXXXX' ],
    pending_connected_team_ids: [],
    is_member: false,
    topic: { value: '', creator: 'XXXXXXXXX', last_set: XXXXXXXXX },
    purpose: {
      value: 'XXXXXXXXX.',
      creator: 'XXXXXXXXX',
      last_set: XXXXXXXXX
    },
    previous_names: [ 'random' ]
  },
  response_metadata: {
    scopes: [
      'identify',
      'channels:history',
      'im:history',
      'mpim:history',
      'channels:read',
      'files:read',
      'groups:read',
      'im:read',
      'mpim:read',
      'users:read',
      'remote_files:read'
    ],
    acceptedScopes: [ 'channels:read', 'groups:read', 'mpim:read', 'im:read', 'read' ]
  }
}
slack-back-static-main/node_modules/@slack/web-api/dist/errors.js:51
    const error = errorWithCode(new Error(`An API error occurred: ${result.error}`), ErrorCode.PlatformError);
                                ^

Error: An API error occurred: user_not_found
    at platformErrorFromResult (slack-back-static-main/node_modules/@slack/web-api/dist/errors.js:51:33)
    at WebClient.apiCall (slack-back-static-main/node_modules/@slack/web-api/dist/WebClient.js:171:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getUserName (slack-back-static-main/app.js:15:25)
    at async /slack-back-static-main/app.js:117:34 {
  code: 'slack_webapi_platform_error',
  data: {
    ok: false,
    error: 'user_not_found',
    response_metadata: {
      scopes: [
        'identify',
        'channels:history',
        'im:history',
        'mpim:history',
        'channels:read',
        'files:read',
        'groups:read',
        'im:read',
        'mpim:read',
        'users:read',
        'remote_files:read'
      ],
      acceptedScopes: [ 'users:read' ]
    }
  }
}

Node.js v18.12.0
```

**Comment by dangarfield** [comment] 2022-11-02 17:35
Very weird, `is_read_only` should be absolutely fine (which I think it is).

I've added a small catch statement to at least get the working channels working so that it processes what it can.
Can you pull and try again. Hopefully you will get the channels that work and if you could let me know if there are many additional problem channels (again, the details will be logged right at the end).

Thanks

**Comment by andystumpf** [comment] 2022-11-02 17:59
Dang. Exact same error.  It did execute for a longer time.
```
  code: 'slack_webapi_platform_error',
  data: {
    ok: false,
    error: 'user_not_found',
    response_metadata: {
      scopes: [
        'identify',
        'channels:history',
        'groups:history',
        'im:history',
        'mpim:history',
        'channels:read',
        'files:read',
        'groups:read',
        'im:read',
        'mpim:read',
        'users:read',
        'remote_files:read'
      ],
      acceptedScopes: [ 'users:read' ]
    }
  }
```

Does it need `data` and `files` folders in the `_static` folder?  It never creates them.  Not sure if it even gets that far.  
```
const DATA_PATH = './_static/data/data.json'
const FILES_PATH = './_static/files'
```

FWIW, I did add `[groups:history]` and still got the error

**Comment by dangarfield** [comment] 2022-11-02 19:52
Another bug, apologies, I wasn't expecting many people to use it. Yes, the data and files folder should be there, do a pull and it'll create them automatically now.

I think that should get further. If you'd like to email me with your credentials (it's relatively safe because the permissions that are given are only read-only, and you can always delete your app and add a new one again anyway), I can have a look into it, alternatively, we could schedule some time to share your screen and I can have look that way.

I'm pretty sure that this should get to the point of at least having a few working channels that you can download and view though.

I can always raise a ticket with slack to see why you're getting the the user_not_found response.

**Comment by dangarfield** [comment] 2022-11-02 20:02
Did you click 'reinstall app' after changing permissions at any point? Just another thought. You have to do that every time.

**Comment by dangarfield** [comment] 2022-11-02 20:31
If you're unhappy about sharing credentials, can you do this:

One last attempt. Can you do a pull.
And also, go into `node_modules/@slack/web-api/dist/WebClient.js` and find line 258.
Replace `this.logger.debug('will perform http request')`
With `this.logger.debug('will perform http request', url, body, headers)`

There should be a lot more logging for each request now and I should see the body and headers that are actually sent. I've also added in the team_id into the request because it seems as though the web-api client did this, but it's not in the documentation as a required field. Either way, it works for me with it in.

**Comment by andystumpf** [comment] 2022-11-02 20:59
Thanks for your time on this!  I'll try the debug you shared.  I'm going to also try another slack workspace to see if there is something specific with the current one.  Thank you!

**Comment by andystumpf** [comment] 2022-11-02 21:18
Here is a sample of the beginning of the debug log.
```
(base) andystumpf@Andys-MBP slack-back-static-main % node app.js
[DEBUG]  web-api:WebClient:0 initialized
[DEBUG]  web-api:WebClient:0 apiCall('conversations.list') start
[DEBUG]  web-api:WebClient:0 will perform http request conversations.list {
  team_id: undefined,
  types: 'public_channel, private_channel, mpim, im'
} {}
[DEBUG]  web-api:WebClient:0 http response received
Fetching channel - CXXXXXXXXK -> Channel: channel-name
[DEBUG]  web-api:WebClient:0 apiCall('conversations.history') start
[DEBUG]  web-api:WebClient:0 will perform http request conversations.history { team_id: 'TXXXXXXXX5', channel: 'CXXXXXXXXK', oldest: 0, limit: 200 } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: ‘XXXXXXXXX } {}
[DEBUG]  web-api:WebClient:0 apiCall('conversations.history') start
[DEBUG]  web-api:WebClient:0 will perform http request conversations.history {
  team_id: 'TXXXXXXXX5',
  channel: 'CXXXXXXXXK',
  oldest: 0,
  limit: 200,
  cursor: 'bmV4dF90czoxNjM2MTXXXXXXXXX'
} {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'XXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'XXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'XXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('conversations.history') start
[DEBUG]  web-api:WebClient:0 will perform http request conversations.history {
  team_id: 'TXXXXXXXX5',
  channel: 'CXXXXXXXXK',
  oldest: 0,
  limit: 200,
  cursor: 'bmV4dF90czoxNjI2MXXXXXXXXX'
} {}
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'XXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'XXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'XXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'XXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'XXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'XXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'XXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'XXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'XXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 apiCall('conversations.history') start
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 will perform http request conversations.history {
  team_id: 'TXXXXXXXX5',
  channel: 'CXXXXXXXXK',
  oldest: 0,
  limit: 200,
  cursor: 'bmV4dF90czoxNjIxMDIyNXXXXXXXXXw'
} {}
```
and finishes with 

```
  team_id: ‘XXXXXXXXX,
  channel: 'XXXXXXXXX',
  oldest: 0,
  limit: 200,
  cursor: 'bmV4dF90czoxNTkyMjMxOXXXXXXXXXw'
} {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('conversations.replies') start
[DEBUG]  web-api:WebClient:0 will perform http request conversations.replies { team_id: undefined, ts: '1666044145.738369', channel: 'XXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'XXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'XXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'XXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('conversations.replies') start
[DEBUG]  web-api:WebClient:0 will perform http request conversations.replies { team_id: undefined, ts: '1625077252.019400', channel: 'XXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'XXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'XXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: undefined } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'XXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'XXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
/slack-back-static-main/node_modules/@slack/web-api/dist/errors.js:51
    const error = errorWithCode(new Error(`An API error occurred: ${result.error}`), ErrorCode.PlatformError);
                                ^

Error: An API error occurred: user_not_found
    at platformErrorFromResult (/slack-back-static-main/node_modules/@slack/web-api/dist/errors.js:51:33)
    at WebClient.apiCall (/slack-back-static-main/node_modules/@slack/web-api/dist/WebClient.js:171:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getUserName (/slack-back-static-main/app.js:17:25)
    at async /slack-back-static-main/app.js:118:36 {
  code: 'slack_webapi_platform_error',
```
I wonder if there are limits that are reached?

**Comment by andystumpf** [comment] 2022-11-02 21:36
https://api.slack.com/docs/rate-limits

There were 906 `apiCall() start` before the error.  

Is there a way to slow the rate of the calls to within the limit?

**Comment by dangarfield** [comment] 2022-11-02 21:43
That's really helpful. I think I know what the issue may be now. Thanks, I'll have another look again tomorrow.

**Comment by andystumpf** [comment] 2022-11-02 22:09
I got a little further using another workspace that has VERY little traffic on it, but it ends in a `sort` error and nothing populates in the slack viewer.  I can delete this and open another issue if that helps to organize it or if it's unrelated to the current issue.

```
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'XXXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
Fetching channel - D01SXXXXXQHX -> IM: Andy Stumpf (XXXXXXXXXX)
[DEBUG]  web-api:WebClient:0 apiCall('conversations.history') start
[DEBUG]  web-api:WebClient:0 will perform http request conversations.history { team_id: 'XXXXXXXXXX', channel: 'D01SPFQFQHX', oldest: 0, limit: 200 } {}
[DEBUG]  web-api:WebClient:0 http response received
       Found  0 messages
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'USLACKBOT' } {}
[DEBUG]  web-api:WebClient:0 http response received
Fetching channel - DXXXXW90 -> IM: Slackbot (USLACKBOT)
[DEBUG]  web-api:WebClient:0 apiCall('conversations.history') start
[DEBUG]  web-api:WebClient:0 will perform http request conversations.history { team_id: 'XXXXXXXXXX', channel: 'DXXXXW90', oldest: 0, limit: 200 } {}
[DEBUG]  web-api:WebClient:0 http response received
       Found  4 messages
[DEBUG]  web-api:WebClient:0 apiCall('files.list') start
[DEBUG]  web-api:WebClient:0 will perform http request files.list { team_id: undefined, page: 1 } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'XXXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 apiCall('users.info') start
[DEBUG]  web-api:WebClient:0 will perform http request users.info { team_id: undefined, user: 'XXXXXXXXXX' } {}
[DEBUG]  web-api:WebClient:0 http response received
filesData { count: 100, total: 35, page: 1, pages: 1 } 2
Combining saved and new channel data
/slack-back-static-main/app.js:75
      channel.messages = channel.messages.sort((a, b) => b.ts.localeCompare(a.ts))
                                          ^

TypeError: Cannot read properties of undefined (reading 'sort')
    at writeData (/slack-back-static-main/app.js:75:43)
    at init (/slack-back-static-main/app.js:197:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.12.0

```

**Comment by dangarfield** [comment] 2022-11-03 09:23
Good news. I think I've solved the issue, it appears to be uncaught errors when there are invalid references to users.
From your logs, I've seen there there can be some `undefined` users somehow. Which also explains why there were 906 `apiCall() start`. I believe this should be resoled. You should see some 'Unknown - XXXXX' or 'Unknown - undefined' users in your channels, but it should work. Please pull and try again, hopefully for the last time!

**Comment by andystumpf** [comment] 2022-11-03 16:07
This is looking 🔥 !  I had to stop it and re-run it without downloading the files since it was HUGE.  I appreciate your time and effort on this. 🥇   Now I just need to figure out how to download just one channel. 🤔

**Comment by dangarfield** [comment] 2022-11-03 16:09
I can add that in if you'd like. Give me 10 minutes

**Comment by dangarfield** [comment] 2022-11-03 17:10
Sorry, was distracted with actual work. Please pull and try again.
You can now add an environment variable for the channel(s) you would like (see readme). It will only download the channel data and files in those channels.
I'll close this ticket, but feel free to raise another, with any feature improvements or bugs.

**Closed as completed by dangarfield** 2022-11-03 17:10 UTC

**Comment by andystumpf** [comment] 2022-11-03 17:25
Thank you!
